name: LoopJournal
options:
  bundleIdPrefix: com.loopjournal
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: J9C5T6SL6B
    CODE_SIGN_STYLE: Automatic
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  LoopJournal:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: LoopJournal
        excludes:
          - "**/.DS_Store"
    resources:
      - path: LoopJournal/PrivacyInfo.xcprivacy
    settings:
      base:
        INFOPLIST_FILE: LoopJournal/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.loopjournal.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: false
        SWIFT_EMIT_LOC_STRINGS: YES
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        CODE_SIGN_IDENTITY: "Apple Development"
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/Frameworks"
    info:
      path: LoopJournal/Info.plist
      properties:
        CFBundleName: LoopJournal
        CFBundleDisplayName: LoopJournal
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UIViewControllerBasedStatusBarAppearance: false
        UIRequiresFullScreen: true
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
        CADisableMinimumFrameDurationOnPhone: true
        UIBackgroundModes:
          - audio
        NSPhotoLibraryUsageDescription: "LoopJournal uses your photo library so you can attach photos to journal entries."
        NSPhotoLibraryAddUsageDescription: "LoopJournal can save a copy of photos you attach to entries into your Photo Library when you turn on \"Save photos to device\" in Settings."
        NSMicrophoneUsageDescription: "LoopJournal uses the microphone to record voice notes for your journal entries."
        NSFaceIDUsageDescription: "LoopJournal uses Face ID to unlock the app when you enable app lock in Settings. Biometric data is not stored or sent anywhere."

  LoopJournalTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: LoopJournalTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: LoopJournal
    settings:
      base:
        INFOPLIST_FILE: LoopJournalTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.loopjournal.app.tests

schemes:
  LoopJournal:
    build:
      targets:
        LoopJournal: [run, test, analyze, profile]
    test:
      gatherCoverageData: false
      targets:
        - LoopJournalTests
